### PR TITLE
A few updates

### LINKED ISSUE #1: Detatch pomo
Fancy terminal tricks to display remaining time etc? having a shell open just for pomo is not ideal

### LINKED ISSUE #23: Alternative notifications (with Quicksilver for example)
I've [forked this gem](https://github.com/mocoso/pomo/tree/quicksilver) to display notification messages with [Quicksilver](http://qsapp.com/).

If there is any appetite for supporting multiple notification systems then I will put together a pull request.

### PR DESCRIPTION
**Pull request by stephenmckinney**
Most likely you're _not_ still supporting this gem, but I've had fun using it and added a few features that made it more useful for myself after seeing the Pomodoro plugin for RubyMine I wanted something similar in iTerm2.

Here's the punchlist:
- Added detach mode, on by default. To get the 1.x progress bar run `pomo start -p`. Closes #1
- Added notification support for Mac OS X User Notifications on OS X 10.8+,
  and libnotify for Linux. Growl continues to be supported on OS X 10.7 or earlier. Closes #23
- Added output of pomo timer to `~/.pomo_stat`. 
- Added `pomo ls` as an alias to `pomo list`

The `~/.pomo_stat` feature enables Tmux status lines, etc. to read this file and display the current time left in a Pomodoro e.g.

Screenshot

Screenshot

Screenshot

in tmux.conf

```
# status bar refresh rate (seconds)
set -g status-interval 3
# right status bar
set-option -g status-right '#[bold]⡇ #H ⡇ #(~/.bin/pomo)  ⡇ #(~/.bin/battery) ⡇ %b %d %I:%M%p '
```

~/.bin/pomo

```
#!/bin/sh

# Display timer as red if less than 5 mins and
# green for greater that 5 mins. 0 is not changed.
echo $(cat ~/.pomo_stat) | \
sed \
-e 's/^\([1-5]\):00/#[default]#[fg=red]\1:00#[default]#[bold]/' \
-e 's/^\([1-9][0-9]\{0,1\}\):00/#[default]#[fg=green]\1:00#[default]#[bold]/'
```

### CODE REVIEW

**Comment by stephenmckinney** [comment]
If you're not interested in maintaining the pomo gem, there are some options:
1. I can take over maintenance and you can give me access to push the gem to rubygems OR
2. I could just make a fork called 'pomo2' or something and push my own gem

I'm interested in adding more features like: `pomo pause/stop`; having pomodoro sets so that you can take a long break after 3 or 4 pomodoros; adding pomo sets, duration, short break, and long break into `.pomorc`, etc.

**Comment by tj** [comment]
im happy to give you access, i dont remember how to do that with gem though

**Comment by stephenmckinney** [comment]
To add me as an owner, you can execute the following:

`gem owner pomo --add stevemckinney@gmail.com`

**Comment by tj** [comment]
hmm apparently my credentials are gone haha, fuck it, ill have to look into it later, centralized registries ftw

**Comment by stephenmckinney** [comment]
LOL. OK. Going to https://rubygems.org/profile/edit under 'API Access' should point you in the right direction.

## 

Steve McKinney

**Comment by tj** [comment]
k done

**Comment by stephenmckinney** [comment]
nice. thx.

**Pull request closed without merging**
