### PR TITLE
add tomatos support?

### PR DESCRIPTION
**Pull request by zlx**
your pomo list can be like this:

``` sh
$ pomo ls
    0. modify for order task                              : 1 tomatos
    1. learn rails activepack                             : 2 tomatos
    2. learn haskell                                      : 1 tomatos
    3. learn programming                                  : 1 tomatos
                                              0 minutes and 5 tomatos
```

### CODE REVIEW

**Comment by jhwist** [comment]
Yes please! +1 on that one.

**Comment by stephenmckinney** [comment]
0 minutes and 5 tomatos? What does a tomato represent?

**Comment by zlx** [comment]
A tomato represent 25 minutes or any piece of time for you. you can focus on work during this time

**Comment by zlx** [comment]
May be you can work with [pomodoro timer](http://linux.softpedia.com/get/Desktop-Environment/GNOME-Shell-Extensions/Pomodoro-93022.shtml) on linux

**Comment by stephenmckinney** [comment]
OK so if a tomato is a unit of work, say 25 mins or even 60 mins. Shouldn't this unit of work be defined in the config not per task?

**Comment by jhwist** [comment]
Yes, ideally I would like to see it like so:
- global configuration for tomato length, default 25minutes
- number of tomatoes estimated for a task
- automatic execution of a 'tomato set', e.g. 4 tomatoes with a 5 minute break after each and a long break (25-30minutes) after the fourth.

I can highly recommend to read http://pragprog.com/book/snfocus/pomodoro-technique-illustrated

**Comment by zlx** [comment]
Good, I highly dependent pomodoro, And now I work with pomo and pomodoro timer in linux. But if pomo can work independent with tomato working style, I'll abandon pomodoro timer.

now for me, pomo notification is weak and auto take break and quick stop is also needed

**Comment by chrismdp** [comment]
:+1: for merging please - this is the one feature that's stopping me using pomo.

**Comment by Schwad** [comment]
Sweet lord that would be amazing.... then I wouldn't have to have a pomo list with some items put 2-6 times in there!

**Comment by Sitebase** [comment]
Awesome suggestion @zlx !

**Pull request closed without merging**
